---
- name: Last Mile OSE Config (Updated for 3.11)
  hosts: localhost
  vars_files:
    - vault.yml
  roles:
    - role: dynamic-inventory
    - role: ipa-openshift

- name: Configure Hosts
  hosts: dynamic_inventory
  roles:
    - role: openshift-prep
