---
- name: Provision Integrated VMs in Bulk
  hosts: localhost
  vars_files:
    - vault.yml
  roles:
    - role: ipam-inventory
      when: ipam_inventory
    - role: ipam-phpipam
      when: ipam_phpipam
    - role: ipa
    - role: rhv
    - role: dynamic-inventory

- name: Configure VMs
  hosts: dynamic_inventory
  vars_files:
    - vault.yml
  roles:
    - role: satellite
  tasks:
    - name: Install ipa-client Package
      yum:
        name: ipa-client
        state: latest

    - name: Register to IdM
      shell: /usr/sbin/ipa-client-install -w "{{ hostvars['localhost']['ipa_otp'] }}" --mkhomedir -U
