---
- name: Provision Integrated VMs in Bulk
  hosts: localhost
  vars_files:
    - vault.yml
  roles:
    - role: ipam-inventory
      when: ipam_inventory
    - role: ipam-phpipam
      when: ipam_phpipam
    - role: ipa
      tags:
        - ipa
    - role: rhv
