---
- name: Populate In-Memory Inventory
  add_host:
    hostname: "{{ item }}"
    ansible_host: "{{ hostvars['localhost']['network_name_dict'][item].ip }}"
    groups: dynamic_inventory
  with_items:
    - "{{ groups[provision_group] }}"
